- pkgs/agenix.nix
fixes #5
@AluisioASG could you please review?
> use only ~/.ssh/id_rsa and ~/.ssh/id_ed25519 for decryption; friendlier error message when no identity

- flake.nix
The example in the README uses `agenix.nixosModules.age` as the NixOS module, but that causes an "attribute 'age' missing" error for me. I've had to use `agenix.nixosModules.x86_64-linux.age` instead. `nix flake show` sees no module in there either:
```
nix flake show 'github:ryantm/agenix'
github:ryantm/agenix/8af97149b28adaf28699af923c35633310d52edf
[…]
├───nixosModules
│   ├───aarch64-linux: NixOS module
│   ├───i686-linux: NixOS module
│   ├───x86_64-darwin: NixOS module
│   └───x86_64-linux: NixOS module
[…]
```
This is because flake-utils doesn't try to distinguish outputs with `${system}` keys from those without.
In my own flakes I've been using a pattern inspired by [this idea for system-dependent and system-independent outputs](https://github.com/NixOS/nix/issues/3843#issuecomment …
> export module as system-independent flake output

- modules/age.nix
The `rootOwnedSecrets`/`nonRootSecrets` logic excluded secrets that are only partly owned by root (i.e. as either user or group, not both). These now run under the latter during activation.
> correctly list non-root secrets

- pkgs/rage.nix
I got a compile error while building the project on macOS 10.15.7.
The error message said something about Foundation missing so I added ` darwin.apple_sdk.frameworks.Foundation` and now the build succeeds.
> Need Foundation to build i18n-embed-fl on darwin

- pkgs/agenix.nix
- pkgs/rage.nix
This PR updates the custom rage package with a fix for aarch64 support. I've also [upstreamed this fix to nixpkgs](https://github.com/NixOS/nixpkgs/pull/111494), so feel free to wait to merge this until that PR is merged.
Since we only need a custom version if the available version has no ssh key support, I changed the `agenix` package to only build a custom `rage` when its version is below 0.5.0. (So users don't have to build `rage` themselves when they are already using unstable).
Fixes #18.
> Fix support for aarch64

- modules/age.nix
rage has a localization crate as a dependency that whines when LANG
is unset.
---
This fixes the slightly annoying (but cosmetic) issue where
```
[ERROR i18n_embed::requester] Unable to parse your locale: ParserError(InvalidLanguage)
```
is spammed to the stage-2 console while decrypting secrets.
> modules/age: set LANG

- modules/age.nix
Otherwise I get annoying `stdenv.lib` warnings because the local package definition uses `stdenv.lib` :)
Mostly lifted from 017422ed4c6b8ffe269a5919c716bfe28ac5df14.
> modules/age: build local rage if pkgs.rage is older than 0.5.0

- modules/age.nix
Seems like some refactoring caused this path to be wrong?
> Fix relative path to `rage.nix`

- example/passwordfile-user1.age
- example/secrets.nix
- modules/age.nix
- test/install_ssh_host_keys.nix
- test/integration.nix
Includes:
* fix: allow deps of installRootOwnedSecrets activation script to be overridden
* feature: use uid 0 and gid 0 as default owner and group (consider them root)
This assumes that the root user is always uid 0 and gid 0, which I
believe is a safe assumption. The reason to add this is because when a
declarative VM (for example, a NixOS test) or image boots the first
time, the installRootOwnedSecrets activation script runs BEFORE the
"users" and "groups" activation scripts, so the user and group for
root is not created. Using uid 0 and gid 0 gets around the root user
not being set up yet.
* dev: add integration test
> add a NixOS test for setting a user's passwordFile with agenix; and some features/fixes this required

- pkgs/agenix.nix
This fixes the following error in non-default environments:
```
/nix/store/p3ijy3qvcqpcxq0ng6x0sm07xg7f751w-agenix/bin/agenix: line 130: diff: command not found
```
> Make 'diff' an explicit dependency

- modules/age.nix
In my environment, secrets are invisible from the activated system due to agenix decrypts secrets before /run mounted.
(EDIT)
This PR is fix for this.
> run activation scripts after /run mount

- README.md
on my system (21.05.1759.91903ceb294 (Okapi)) I needed to add the .nix extensions on age to get nixos-rebuild to find the module. This seems to be inline with the modules directory structure:
`modules/age/nix`
rather than
`modules/age/default.nix`
but I'm not an expert on nix's file naming conventions.
I did not test the other ways of installing agenix  but am happy to run through them if this is a desired change.
> add .nix extensions

- modules/age.nix
This is meant to be a temporary workaround while we add support for dry activation scripts in #56 .
> fix: workaround for #54

- modules/age.nix
https://github.com/NixOS/nixpkgs/pull/137508 should remove the need
for this.
I confirmed this works without the workaround in the latest nixos-unstable with https://github.com/NixOS/nixpkgs/pull/137508
closes #54
> fix: remove workaround for #54

- README.md
- modules/age.nix
This follows sops-nix's implementation, where it creates a
`/run/secrets.d` ramfs mountpoint and a "generation" each time
the activation script runs, and then symlinks `/run/secrets` to
`/run/secrets.d/[generation]`.
---
Fixes #26.
Fixes #21.
---
~~TODO (maybe): is it possible to not create a new generation each time activation runs (if nothing changed)? Does sops-nix do this?~~ While possible, this would introduce a decent amount of complexity for (IMHO) no gain. Since we remove old secrets generations, I think this is unnecessary.
> modules/age: symlink files into place

- README.md
Fix installation instructions for channel installation, now that the default branch name has changed.
> Install instructions: master -> main

- README.md
I had a small PEBMAC ("problem exists between monitor and chair") issue before realizing that `config` needs to be prefixed to `age.secrets.<name>.path`, so to clarify I thought we might add that to the readme.
> README: clarify that 'config' has to be prefixed

- README.md
- modules/age.nix
- pkgs/agenix.nix
I have an old VPS which don't have a `avx2` CPU instruction. Rage won't decrypt anything on it.
```console
[nix-shell:~]$ sudo rage -i /etc/ssh/ssh_host_ed25519_key -d test.age
Illegal instruction
```
However, the [official Go implementation](https://github.com/FiloSottile/age) works well. In this PR, I add the capability for user to customize what implementation to use.
```nix
{
age.ageBin = "${pkgs.age}/bin/age";
environment.systemPackages = [
(agenix.defaultPackage.x86_64-linux.override { ageBin = "${pkgs.age}/bin/age"; })
];
}
```
> Allow customizing ageBin

- modules/age.nix
Otherwise /run/agenix might disappear if specialfs is toposorted between agenixMountSecrets and agenixRoot.
Fixes: https://github.com/ryantm/agenix/issues/92
> Ensure /run is created before mounting secrets

- flake.nix
This adds a “default” NixOS module in flake.nix. This makes using this in flakes a little less verbose and repetitive.
Before this change:
```nix
nixpkgs.lib.nixosSystem {
modules = [
./configuration.nix
agenix.nixosModules.age
];
}
```
After this change:
```nix
nixpkgs.lib.nixosSystem {
modules = [
./configuration.nix
agenix.nixosModule
];
}
```
> Add default NixOS module to flake

- modules/age.nix
rage itself does not have good error messages when files are missing,
so add some of our own checks and warnings.
I haven't had a chance to test this yet.
> feature: warn about missing files

- modules/age.nix
- test/install_ssh_host_keys.nix
This simplifies agenix by combining the root and nonRoot secret installation into one place and delays setting the owner and group of the secrets until after the users and groups activation scripts are completed. This also fixes #117 by incorporating the changes from #118 to not switch over the secret directory symlink until after the secrets are decrypted. 
This is a **breaking change** in the sense that someone might have depended on the user or group of a root secret being set before the "users" and "groups" activation scripts run, but that seems unlikely to me.
This is also a **breaking change** because I renamed a bunch of the activation scripts. I believe these will be module compile-time errors.
cc @jsimonetti
> feature: combine root and nonroot secret install; delay chowning

- flake.lock
- flake.nix
22.11 is almost out. 21.11 has been deprecated. 
Since `nixpkgs` was so out of date, the deprecation warnings alluded to in #126 were not clear here.
> Track `nixos-unstable` channel as `nixpkgs`

- README.md
- flake.lock
- flake.nix
* New flake output format, and the old one causes warnings on recent versions of nix
* Remove extraneous quotes from the flake.nix
* Now that all maintained versions of nixpkgs have the features we need, we don't need an explicit nixpkgs input
* Update docs for the new output format
closes #126
> feature: update flake output format and docs

- .github/workflows/ci.yaml
- README.md
- default.nix
- example/secrets.nix
- flake.nix
- modules/age.nix
- overlay.nix
- pkgs/agenix.nix
- pkgs/rage.nix
- test/install_ssh_host_keys.nix
- test/integration.nix
* Add new contributing docs
* Choose Alejandra as Nix formatter
* Add formatter to flake so nix fmt works
* Add CI lint step for nix fmt checking
* Format all nix files
---
Depends on https://github.com/ryantm/agenix/pull/136
> contrib: format with Alejandra

- README.md
as suggested in #133
@RuRo please review!
> doc: collapse installation sections

- modules/age.nix
- test/integration.nix
- test/integration_darwin.nix
- Test with nonexisting key
- Skip missing or unreadable keys
Fixes https://github.com/ryantm/agenix/issues/116
> Skip missing or unreadable keys

- pkgs/agenix.nix
- pkgs/agenix.sh
I want to move toward a world where we test the agenix cli. I feel this is a reasonable organizational step, so we can separate the nix code from the bash code.
> contrib: use mkDerivation for agenix cli 

- test/install_ssh_host_keys.nix
- test/integration.nix
This PR
- adopts the tests for linux to use the new-style tests
- adds the CLI to the integration tests
- adds an example CLI test for the `--rekey` function
Let me know what you think about this approach -- I'm kind of excited. If there are no major concerns I'll be happy to chip away at adding a few additional tests and seeing whether I can sort out the darwin tests as well.
> Expand tests

- pkgs/agenix.sh
- test/install_ssh_host_keys.nix
- test/integration.nix
fixes #151
* Adds some basic tests for editing
* Changes agenix to not add the default identity locations, if one is specified with -i
> fix: if an identity is specified, don't use the default ones

- modules/age.nix
The provided `isDarwin` check failed on my system because `environment` attr does not exist in `options`.
I assume that this happens because my setup is done with divnix/hive (https://github.com/divnix/hive), but I am not an expert :) (I see this PR as an opportunity to learn :); so close if I naivly do something totally wrong :) ).
Nevertheless, it is probably not a bad idea to only assume the most essential attrs to be present.
> Make isDarwin check more robust

- pkgs/agenix.sh
- test/install_ssh_host_keys.nix
- test/integration.nix
If STDIN is not interactive, change EDITOR to `cp /dev/stdin`.
Also updates tests somewhat.
fixes #33
> feature: pipe cleartext into agenix -e

- pkgs/agenix.sh
- Redirect user-directed warnings to stderr
- Add warn and err helpers, use `diff -q`
This helps make it more feasible to use e.g. `agenix --decrypt` in a script,
since capturing its stdout will no longer get all the warning messages.
> Output user-facing warnings to stderr instead of stdout

- README.md
- pkgs/agenix.sh
- test/integration.nix
See https://github.com/ryantm/agenix/pull/154#issuecomment-1437566317 for some discussion.
The implementation is not super pretty, but works. Feel free to pick on the style.
I also replaced one of the `EDITOR=cat` invocations in the integration test with usage of this option.
Speaking of which, that test takes forever to run for me, it seems to wait for 5 minutes for sshd to time out. Is that expected? Maybe something related to missing entropy?
> add -d/--decrypt option to decrypt a file to stdout

- pkgs/agenix.sh
I had first used `printf` for outputting the data, but that breaks if the secret itself contains null bytes.
One could fix this by using e.g. `cat`, but looking a bit more at the code I realized that in the -d case we never need to `mktemp` at all and can just ask `age` to write directly to stdout by not setting -o.
> fix -d/--decrypt-only not working correctly for binary data

- README.md
Fixes https://github.com/ryantm/agenix/issues/165
Fixes https://github.com/ryantm/agenix/issues/166
> Expand explanation that identityPaths should be strings

- .github/workflows/ci.yaml
- .github/workflows/doc.yml
- doc/acknowledgements.md
- doc/community-and-support.md
- doc/contributing.md
- doc/features.md
- doc/install-via-fetchtarball.md
- doc/install-via-flakes.md
- doc/install-via-niv.md
- doc/install-via-nix-channel.md
- doc/introduction.md
- doc/notices.md
- doc/overriding-age-binary.md
- doc/problem-and-solution.md
- doc/reference.md
- doc/rekeying.md
- doc/threat-model-warnings.md
- doc/toc.md
- doc/tutorial.md
- flake.lock
- flake.nix
- pkgs/doc.nix
* use mmdoc
* add github pages action to auto publish
* do not edit README for now, will follow up with a commit directs people to the doc site
> doc: add new doc website

- pkgs/agenix.sh
rage intentionally truncates large output when writing to stdout: https://github.com/str4d/rage/blob/55e52c252b4036eb76582c84cbc5b9f6ef23c67f/age/src/cli_common/file_io.rs#L219
but if told to write to "-" instead, it will not truncate: https://github.com/str4d/rage/blob/55e52c252b4036eb76582c84cbc5b9f6ef23c67f/age/src/cli_common/file_io.rs#L312
> fix truncated output when decrypting a large file to stdout via -d

- .github/workflows/ci.yaml
- flake.lock
- flake.nix
- modules/age-home.nix
- test/install_ssh_host_keys_darwin.nix
- test/integration.nix
- test/integration_darwin.nix
- test/integration_hm_darwin.nix
This is to update and fix the issues I saw in [1] and [2].
Using a service definition instead of an activation script should resolve the issue about the secrets disappearing after rebooting.
Removed the `user` and `group` option as they do not make sense to me for a home-manager module, which should target a single user. They can always be added back if somebody comes screaming.
This is somewhat modeled after sops-nix's own module [3].
[1]: https://github.com/ryantm/agenix/pull/58/
[2]: https://github.com/ryantm/agenix/pull/109
[3]: https://github.com/Mic92/sops-nix/blob/master/modules/home-manager/sops.nix
> Add home-manager module

- modules/age-home.nix
- modules/age.nix
Please refer to commit messages for more info.
> doc: fix defaultText and description

- modules/age-home.nix
If you set `secretsDir` in the home-manager module to a fixed path containing no env variable, the building of the mount script will fail with shellcheck warnings like these (for `/home/eisfunke/.agenix` as `secretsDir`):
```
In /nix/store/sh4igrd310v01nlfdgw9fw7qb9ck30wm-agenix-home-manager-mount-secrets/bin/agenix-home-manager-mount-secrets line 101:
[ "/home/eisfunke/.agenix/nixNetrc" != "/home/eisfunke/.agenix/nixNetrc" ] && mkdir -p "$(dirname "/home/eisfunke/.agenix/nixNetrc")"
^-- SC2050 (warning): This expression is constant. Did you forget the $ on a variable?
In /nix/store/sh4igrd310v01nlfdgw9fw7qb9ck30wm-agenix-home-manager-mount-secrets/bin/agenix-home-manager-mount-secrets line 112:
[ "/home/eisfunke/.agenix/nixNetrc" != "/home/eisfunke/.agenix/nixNetrc" ] && ln -sfn …
```
> fix(home): shellcheck failure for fixed secretsDir

- pkgs/agenix.nix
- pkgs/agenix.sh
Fixes https://github.com/ryantm/agenix/issues/147
> contrib: use jq instead of sed

- pkgs/agenix.sh
If a user has a `secrets.nix` that uses `builtins.readFile` to set the value of a key, as such:
```
let
system = builtins.readFile ../hosts/server/ssh_host_ed25519_key.pub;
in
{
"rootPassword.age".publicKeys = [ system ];
}
```
an error occurs:
```
❯ nix-instantiate --eval --json secrets.nix
error:
… message for the trace
at /home/will/Projects/nixos-config/secrets/secrets.nix:10:3:
9| {
10|   "rootPassword.age".publicKeys = system;
|   ^
11| }
error: cannot convert a thunk to JSON
at /home/will/Projects/nixos-config/secrets/secrets.nix:10:3:
9| {
10|   "rootPassword.age".publicKeys = system;
|   ^
11| }
```
adding `--strict` fixes this
> fix: add --strict nix-instantiate to support builtins.readFile

- pkgs/agenix.sh
When you do not have your pubkeys in your `secrets.nix` verbatim as string but read them from file like this: `desktop1 = builtins.readFile ./desktop1.pub;`, you will end up with empty newlines in the resulting list of keys, which will add `--recipient=''` arguments to your age call, failing the call.
> feat: remove empty newlines from jq query

- pkgs/agenix.sh
Avoids complaints from `cp` about nonexistent files.
> only backup cleartext file if it exists

- .github/workflows/ci.yaml
- pkgs/agenix.nix
These tests are MUCH faster than the NixOS tests.
> contrib: add direct tests for agenix 

- flake.lock
- flake.nix
Why
===
* flake.nix had a lot of almost redundant lines in it.
* i686 support is probably being dropped soon in nixpkgs https://github.com/NixOS/nixpkgs/pull/266164
What changed
==
* Add new input nix-systems/default which represents the default systems typically used in the Nix community
* Define and use an eachSystem function that simplifies the flake.nix file
> dev: remove i686 support; simplify flake

- .github/workflows/ci.yaml
- README.md
- doc/notices.md
- doc/reference.md
- flake.lock
- flake.nix
- modules/age-home.nix
- modules/age.nix
- pkgs/agenix.nix
Why
===
* Someone said age works better with password protected keys, requiring entering the password less often.
* We switched to rage from age in https://github.com/ryantm/agenix/commit/07ce686870f52a7397164b755d721bc85f110aac because it was limiting recipients to 20. This was fixed https://github.com/FiloSottile/age/issues/139
What changed
===
* Switch from rage back to age (the reference implementation) in all the spots
* Update the docs to show how to switch back to Rage
> feat: switch from rage to age

- .github/workflows/ci.yaml
- pkgs/agenix.nix
Why
===
* We'd like some tests for the CLI
* Last time we tried it failed on macos
What changed
===
* This time, we try to create the temp directory in a way that works
with macos too
> dev: reland add direct tests for agenix

- doc/overriding-age-binary.md
I'm not sure if /how `doc/overriding-age-binary.md` is used. If it's not used maybe it should be removed, since the same info exists in `README.md`, which got me confused initially and prompted this pr.
> fix: update docs for 5c1198a

- README.md
`ssh-keyscan` seems doesn't accept the format `user@address`.
See <https://man.openbsd.org/ssh-keyscan.1>
> doc: fix wrong `ssh-keyscan` usage

- pkgs/agenix.sh
Previously, empty lines in the keys would be interpreted as a recipient key, leading to the error message `age: Error: unknown recipient type: ""`. This is easy to do if you keep your ssh keys in separate files then add them to secrets.nix using `builtins.readFile`, since editors like vim will add an invisible newline to the end of every file. (unless you set noeol)
This fixes the issue by ignoring empty lines.
> fix: allow for newlines in keys

- pkgs/agenix.nix
As opposed to e.g. Nix 2.18, Nix 2.3 doesn't try to create a fallback store in $HOME if $NIX_STORE_DIR and $NIX_STATE_DIR aren't writable.
> agenix: fix installCheckPhase with Nix 2.3

- modules/age-home.nix
- modules/age.nix
If a secret is used in the initrd with stage1 systemd, it will be copied into the initrd on activation time, after agenix has run. If the system is then restarted, the directory /run/agenix will be created by the initrd because the file is included in the cpio archive. This will in turn cause agenix to silently create an incorrect link `/run/agenix/0 -> /run/agenix.d/0` instead of `/run/agenix -> /run/agenix.d/0` when switching to stage2.
Technically this is not a bug in agenix, since including a secret under `/run/agenix` can be considered invalid use. Yet I believe it would be good if agenix errors in such cases instead of creating a wrong link, to make users aware of the issue. Therefore I propose to replace `ln -sfn` with `ln -sfT` which will unconditionally treat the target as a …
> fix: always treat link destinations as files to ensure an error when the destination is a directory

- flake.nix
When using `files` on a NixOS option in the `nix repl` it fails to follow the attribute of agenix module.
Discussing with @roberth has explained that this is a "common bug" on account of mis-using the `import` for modules.
From what I understand, the `import` statement brings it into the current context so you lose the attribute of where it's defined.
Here is what I currently see:
```
nix-repl> options.age.ageBin.files
[
"/nix/store/8kpmdb63f5i9mwdyirqki7hvvglgy1va-source/machines/nyx/configuration.nix"
]
```
After this change, the value in agenix is reported instead.
```
❯ nix repl --extra-experimental-features 'flakes repl-flake' \
--override-input agenix /home/fmzakari/code/github.com/ryantm/agenix .
nix-repl> options.age.ageBin.files
[ …
```
> Remove import for NixOS/HM modules

- modules/age-home.nix
To avoid having to do https://github.com/colonelpanic8/dotfiles/blob/4fd99eae63ef0ea8e6f23ac5e152352cb0fc1bf0/nixos/secrets.nix#L25C9-L29C116 while using agenix in user services.
Relevant discussion in NixOS chat: https://matrix.to/#/!RRerllqmbATpmbJgCn:nixos.org/$y_A0dX6Kj0TFTCCxQIXIK9VgqwzPXjBoZLCGbzmUxBA?via=nixos.org&via=matrix.org&via=tchncs.de
Heads-up: @colonelpanic8
> age-home: Use curly-brackets for XDG_RUNTIME_DIR

- .github/workflows/ci.yaml
- modules/age.nix
Since LnL7/nix-darwin#1172, `services.openssh.enable` is introduced for Darwin with default value being `null` instead of a boolean. `services.openssh.hostKeys` is still not available on Darwin.
The default value of `age.IdentityPaths` assumes `services.openssh.enable` being a boolean, causing evaluation failure on Darwin if not explicitly defined.
This PR attempts to:
* Fix above issue.
* Ensures `services.openssh.hostKeys` could be picked up for Darwin if it is implemented in the future.
* Bumps `macOS-12` to `macOS-15` in CI because it is deprecated by GitHub.
> fix: bad age.identityPaths default value on darwin, bump to macOS-latest in CI

- example/-leading-hyphen-filename.age
- example/secrets.nix
- pkgs/agenix.sh
- test/integration.nix
This prevents interpreting filenames with leading `-` as flags.
Add a regression test for this behavior.
Fixes https://github.com/ryantm/agenix/issues/325
> Separate flags from positional args with `--`

- README.md
People's editors keep automatically doing this and adding a bunch of
unrelated lines to their diff. Trying to stop that.
> doc: strip trailing whitespace

- modules/age.nix
This error can be puzzling if you're not already aware of how this works, pointing users in the direction of openssh (which I suspect is the most common way to populate `identityPaths`) while also keeping the original message seems instructive.
> Improve `age.identityPaths must be set` error

- doc/overriding-age-binary.md
Also format codeblock RFC style, use `lib.getExe`
re: https://github.com/ryantm/agenix/pull/330
> doc: clarify lack of support when using nondefault implementations
